---
:concurrency: 4
development:
  :concurrency: <%= ENV['SIDEKIQ_CONCCURENCY'] || 4 %>
staging:
  :concurrency: <%= ENV['SIDEKIQ_CONCCURENCY'] || 2 %> # times 4 dynos = 8 threads
production:
  :concurrency: <%= ENV['SIDEKIQ_CONCCURENCY'] || 2 %> # times 4 dynos = 8 threads